### ISSUE TITLE
No module named 'Resolver'

### ISSUE THREAD

**Issue by 777string** [BishopFox/spoofcheck#1]
Get the following error when running ./spoofcheck.py domainname.com

Windows 10
Python 3.5.2
antivirus disabled

```
Traceback (most recent call last):
  File "./spoofcheck.py", line 7, in <module>
    import emailprotectionslib.dmarc as dmarclib
  File "C:\Users\user1\AppData\Local\Programs\Python\Python35-32\lib\site-packages\emailprotectionslib\dmarc.py", line 3, in <module>
    import Resolver
ImportError: No module named 'Resolver'
```

**Comment by colinking** [comment]
Didn't spend much time looking into this, but believe it is a Python 3 vs Python 2 issue. Works on Python 2.7.13.

https://github.com/lunarca/pyemailprotectionslib/issues/1

**Comment by lunarca** [comment]
At the moment, only Python 2.7 is supported. 3.5+ support is in the works.

**Comment by Switch1024** [comment]
> At the moment, only Python 2.7 is supported. 3.5+ support is in the works.

still not fixed?
